# Default values for Alfresco Process Services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
registryPullSecrets: quay-registry-secret

processEngine:
  replicacount: 1
  image:
    repository: alfresco/process-services
    tag: "1.9.0.5"
    pullPolicy: IfNotPresent
    internalPort: 8080
  service:
    name: aps
    type: NodePort
    externalPort: 80
  environment:
    ACTIVITI_DATASOURCE_DRIVER: "org.postgresql.Driver"
    ACTIVITI_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
    IDENTITY_SERVICE_ENABLED: "false"
    IDENTITY_SERVICE_REALM: "alfresco"
    IDENTITY_SERVICE_SSL_REQUIRED: "none"
    IDENTITY_SERVICE_RESOURCE: "alfresco"
    IDENTITY_SERVICE_PRINCIPAL_ATTRIBUTE: "email"
    IDENTITY_SERVICE_ALWAYS_REFRESH_TOKEN: "true"
    IDENTITY_SERVICE_AUTODETECT_BEARER_ONLY: "true"
    IDENTITY_SERVICE_TOKEN_STORE: "session"
    IDENTITY_SERVICE_ENABLE_BASIC_AUTH: "true"
    IDENTITY_SERVICE_PUBLIC_CLIENT: "true"
    ACTIVITI_CORS_ENABLED: "true"
    ACTIVITI_CORS_ALLOWED_ORIGINS: "*"
    ACTIVITI_CORS_ALLOWED_METHODS: "GET,POST,HEAD,OPTIONS,PUT,DELETE"
    ACTIVITI_CORS_ALLOWED_HEADERS: "Authorization,Content-Type,Cache-Control,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,X-CSRF-Token"
    ACTIVITI_CSRF_DISABLED: "false"
    ACTIVITI_ES_SERVER_TYPE: "embedded"
    ACTIVITI_ES_CLUSTER_NAME: "elasticsearch"
    ACTIVITI_ES_DISCOVERY_TYPE: "unicast"
    ACTIVITI_ES_DISCOVERY_HOSTS: "localhost:9300"
    IDENTITY_SERVICE_AUTH: "http://localhost:8080/auth"

license:
  secretName: none

ingress:
  path: /activiti-app

persistence:
  existingClaim: "alfresco-volume-claim"
  mountPath: "/usr/local/data"
  subPath: "alfresco-process-services/process-data"

alfresco-process-services:
  alfresco-infrastructure:
    enabled: true
    
adminApp:
  replicacount: 1
  image:
    repository: alfresco/process-services-admin
    tag: "1.9.0.1"
    pullPolicy: IfNotPresent
    internalPort: 8080
  service:
    name: aps-admin
    type: NodePort
    externalPort: 80
  ingress:
    path: /activiti-admin
  environment:
    ACTIVITI_ADMIN_DATASOURCE_DRIVER: "org.postgresql.Driver"
    ACTIVITI_ADMIN_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
    ACTIVITI_ADMIN_REST_APP_HOST: "http://localhost"
    ACTIVITI_ADMIN_REST_APP_PORT: "80"
    ACTIVITI_ADMIN_REST_APP_USERNAME: "admin@app.activiti.com"
    ACTIVITI_ADMIN_REST_APP_PASSWORD: "admin"

processWorkspace:
  replicacount: 1
  image:
    repository: quay.io/alfresco/alfresco-process-workspace-app
    tag: "1.3.2"
    pullPolicy: IfNotPresent
    internalPort: 80
  service:
    name: apw
    type: ClusterIP
    externalPort: 80
  ingress:
    path: /
  environment:
    APP_CONFIG_BPM_HOST: '{{ tpl (.Values.ingress.hostName | default "http://localhost") . }}'
    BASE_PATH: "{{ .Values.processWorkspace.ingress.path }}" # TODO needs support in Docker image
    APP_CONFIG_AUTH_TYPE: "BASIC" # i.e. BASIC | OAUTH
    APP_CONFIG_PROVIDERS: "BPM"
    APP_CONFIG_ECM_HOST: "http://ecmhost"
    APP_CONFIG_OAUTH2_HOST: "http://oauth2host/auth/realms/alfresco"
    APP_CONFIG_OAUTH2_CLIENTID: "activiti"

postgresql:
  enabled: true
  nameOverride: postgresql-aps
  postgresUser: alfresco
  postgresPassword: alfresco
  imageTag: "9.4.6"
  postgresDatabase: activiti-admin

alfresco-infrastructure:
  rabbitmq-ha:
    enabled: false
  activemq:
    enabled: false
  alfresco-activiti-cloud-registry:
    enabled: false
  alfresco-api-gateway:
    enabled: false
  alfresco-identity-service:
    enabled: false

