apiVersion: v1
kind: Service
metadata:
  name: {{ template "aps.fullname" . }}-aps
  labels:
    app: {{ template "aps.fullname" . }}-aps
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.processEngine.service.type }}
  ports:
    - port: {{ .Values.processEngine.service.externalPort }}
      targetPort: {{ .Values.processEngine.image.internalPort }}
      name: {{ .Values.processEngine.service.name }}
  selector:
    app: {{ template "aps.fullname" . }}-aps
    release: {{ .Release.Name }}
