apiVersion: v1
kind: Service
metadata:
  name: {{ template "aps.fullname" . }}-apw
  labels:
    app: {{ template "aps.fullname" . }}-apw
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.processWorkspace.service.type }}
  ports:
    - port: {{ .Values.processWorkspace.service.externalPort }}
      targetPort: {{ .Values.processWorkspace.image.internalPort }}
      name: {{ .Values.processWorkspace.service.name }}
  selector:
    app: {{ template "aps.fullname" . }}-apw
    release: {{ .Release.Name }}